### ISSUE TITLE
Chat auto-scrolling not working

### ISSUE THREAD

**Issue by babel2uk** [n3dst4/gumshoe-fvtt#1007]
I'm not sure if this is a bug or a setting that's been changed. Every other game I have on Foundry, the chat panel autoscrolls to show the most recent message. For some reason my Gumshoe game doesn't.

Thanks
Matt

**Comment by babel2uk** [comment]
Weirdly this appears to have fixed itself. I have no idea why it wasn't working, or why it's suddenly working again.

**Comment by n3dst4** [comment]
Weird! Now you say it I feel like I've experienced it, but usually when I'm mid-session and don't have time to investigate*. Please feel free to re-open this if you see it again.

* pun intended
