### ISSUE TITLE
Simple sheet for users with *Limited* rights

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#235]
It would be cool to have NPC-Documents that react to the users privileges: 

USE-Case: I hab a load of NPCs which i would like to show to my players but only in basic aspects (Portrait, Name, Description). 

In Call of Cthulhu this can be done by setting the Rights for the NPC to "Limited" for all Players. 
It is then visible in the sidebar and a click opens a very simple (Portrait only) version of the sheet). 

It would be great to have this in Gumshoe, especially as AI allows for individual Portraits for virtually every NPC. Extending this feature to Name and description would be even greater. 

BTW: keep up the good work. Still a fan :)

**Comment by n3dst4** [comment]
Great idea! I didn't even know this was possible.

**Comment by Muwak77** [comment]
I hope thats not too pushy, but is this still on the table? 

I've done some resarch and checking for 

`  if (!entity.testUserPermission(game.users.curr  if (!entity.testUserPermission(game.users.current, game.settings.get('journal-backlinks', 'PERMISSONLEVELHERE'))) ent, game.settings.get('journal-backlinks', 'PERMISSONLEVELHERE'))) `

and then just display the image and maybe notes should do the trick. 

If it helps i can implement it and send a pull request but i did not want to mess with your project without asking :)

**Comment by n3dst4** [comment]
Please do!

My approach would be: 

1. Copy `NPCSheet` to something like `NPCSheetFull`.
2. Create a new component called something like `NPCSheetSimple` with the simplified view in there.
3. Remove the content from `NPCSheet` and put the conditional test there instead.

This way we're not adding extra complexity to the main `NPCSheet`.

**Comment by Muwak77** [comment]
Sounds good to me. I'll send a pull-Request as soon as i have figured out sth decent  :)

**Comment by Muwak77** [comment]
I have some Issues with my Pull Request which is probably beacause i am rather new to Github (also to React btw. ). But i attached with what i came up with. Hope this is useful: 

[npcSheet.zip](https://github.com/n3dst4/gumshoe-fvtt/files/13264162/npcSheet.zip)

**Comment by n3dst4** [comment]
So I took your version and ran with it https://github.com/n3dst4/gumshoe-fvtt/pull/542

Main changes from yours:

* I changed the image picker (I don't know why I called it ImagePickle but I'm not changing it now) so if you are "limited" or "observer", it just opens the image, no option to edit.
* I changed the permission level to get the simple sheet to just LIMITED (so OBSERVER can still see the full sheet)
* I tweaked the layout of the simple NPC sheet so you get a large portrait if there's no text, and a slightly smaller one if there is text.

**Comment by Muwak77** [comment]
Great thank you so much for adding this, can't wait for the release :)
