### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by marksjus** [n3dst4/gumshoe-fvtt#246]
I've redacted and corrected Polish lang file. I've also added missing entries. (For some unknown reason adding second lang path leading to moribundWorld/pl.json does not work so translated entries from there are in the main file)

Found issues:
1. In "NPS sheet":  'Use ammo?', 'Current', 'Maximum' and in "PC sheet": 'Occ.', 'Rating', 'Injury Status', 'Items' tab from Moribund World are hard coded and cannot be translated (or I'm missing something).
2. I can't translate "Use Turn-Passing Initiative?" because I don't know what it does.
3. Ability categories are not translated by Babele because they're set in the configuration menu of the system. Manual translation of categories in the config menu results in doubling the category on the sheet, both in English and in Polish (and probably in other languages). Proposed solution will be changing category name in compendium pack to category ID and get name from config or I can provide you a polish compendium pack with translated categories but that's a patch not a fix.
4. All hard coded entries in config menu (Occupation, Occupational Benefits, Pillars of Sanity, Sources of Stability, categories, abilities, etc.) have to be manually translated by the user in the menu.

That's all (for now ;) ) feel free to disregard some or all of the above :D

[lang.zip](https://github.com/n3dst4/gumshoe-fvtt/files/11651862/lang.zip)

**Comment by n3dst4** [comment]
Going to mark this as done because the main changes are merged, but if you come uip with a translation for "Use Turn-Passing Initiative?" you can put in a comment here and I'll add it by hand.

**Comment by n3dst4** [comment]
Actually 3 is weird - it seems to partially work if the Babele translation has a translation for the category name. Here's french (after clicking the "translate" button at the top of the chatracter sheet:


![Image](https://github.com/n3dst4/gumshoe-fvtt/assets/280206/97e26e10-2cdb-42a0-9ca4-881ad20ea192)


I'll have a proper look into it tomorrow.

**Comment by marksjus** [comment]
Ad. 2. Thanks, now I get it.
Ad. 3. You're right, abilities are translated automatically if there is a translation in the compendium. Categories are translated manually after clicking on 'translate', but for me it only works for French (I've checked Polish, Spanish, and Japanese). It's weird.

**Comment by marksjus** [comment]
I've checked v7.1.0-alpha.1, everything working as intended. I'll add missing entries, make translation file for Moribund World and send you the files. For Trail of Cthulhu there is an official translation now since it was published in Poland so that will be quick, the rest will probably takes some more time.

**Comment by n3dst4** [comment]
Thank you! I haven't even tested 7.1.0-alpha.1 myself yet :)

If you like, you can work from https://explore.transifex.com/investigator-system/investigator-system/ (but feel free to just edit JSON if that's easier.)

**Comment by n3dst4** [comment]
If you do use Transifex, I've added the Moribund World strings there too.

**Comment by marksjus** [comment]
Sorry, I had some free time and I got curious :) I can wait for the stable release of course.

I prefer editing JSON if that's ok. That way I've got real time preview in the Foundry whether everything is working.

**Comment by n3dst4** [comment]
Yeah, that makes sense :) 

And I'm happy to have you testing the alpha, I don't usually get much uptake on alphas so I stopped broadcasting them.

Any chance you're testing on Foundry v11? 7.1.0 *should* be safe on v11.

**Comment by marksjus** [comment]
No, I'm using V10, but if you're saying it should work I could test it on V11.

**Comment by n3dst4** [comment]
Yes please

**Comment by marksjus** [comment]
Done. All compendiums and Moribund World (just add the lang path to system). One issue though, 'name' for person and 'name' for things is different in Polish. It looks like you named the item.

I've found no issue with v11 whatsoever. But I've found that when you open the system for the first time, it's configured for ToC and the 'Drive' string in config in 'personal details' is missing. When you change 'system preset' to something else and then to ToC again 'drive' is put correctly.

BTW. Is there a reason to separate  'personal details' and 'occupational label'? I'm asking because ''occupational label' in Ashen Stars is 'Species' and it looks funny.

[lang.zip](https://github.com/n3dst4/gumshoe-fvtt/files/11778731/lang.zip)

**Comment by marksjus** [comment]
You didn't add moribundWorld/pl.json path to system.json.

On a positive note: I plan to make translation of The Esoterrorists' abilities on saturday, so I can also prepare the source file for babele.

**Comment by n3dst4** [comment]
Doh!

**Comment by n3dst4** [comment]
7.2.1 is out 😋

**Comment by marksjus** [comment]
now it's ok :D btw. I've modified 'ItemSheet' to distinguish between person's name and item's name, and I've added 'ItemName' variable to translation files. I'll send it on saturday with the Esoterrorists.

Still can't figur out why 'personal details' name string is empty in default configuration, while it should be 'Drive' and it say so in the default value.

**Comment by n3dst4** [comment]
I love the thing of having different words for "name". An old friend from krakow told me that Polish has different words for "face" depending on the type of animal. He used to call his wife the word that means the kind of face a rodent has (like a cute, affectionate name).

**Comment by marksjus** [comment]
True, words like 'pyszczku' or 'mordko' are often used that way. Truth be told, we can make cute versions of almost every animal name or its part 😀
