### ISSUE TITLE
The Esoterrorists support

### ISSUE THREAD

**Issue by tbsvttr** [n3dst4/gumshoe-fvtt#261]
The Esoterrorists had been the first GUMSHOE game. But sadly, it seems to be completely missing from this module. We entered all the abilities and configured them to the correct category. Also, we made Health and Stability trackable. I hope this can be added to the module itself, so other people do not have to do this again. There might be some additional work to be done with this, but I think it still will help. If I do any improvements to it, I will post them here again.

[esoterrorists-abilities.json.zip](https://github.com/n3dst4/gumshoe-fvtt/files/11754947/esoterrorists-abilities.json.zip)

**Comment by n3dst4** [comment]
That's fantastic. I was just saying on the Pelgrane Discord the other day, it was weird that I hadn't done Esoterrorists yet.

**Comment by tbsvttr** [comment]
@n3dst4 I had a look at your source-code. It's rather clean and modular. If it helps you out, I can also provide this as a PR?

**Comment by n3dst4** [comment]
That would be great. The other thing we would need (if you feel inclined) is a settings preset, which should be fairly default (I don't think Esoterrorists has many non-standard rules.)

**Comment by tbsvttr** [comment]
@n3dst4 I need to look into the second part both in terms of your code and my rules knowledge of the RPG system. But the first part I will deliver this week.

**Comment by n3dst4** [comment]
I'm hijacking this issue to represent more general Esoterrorists support. If you do start on the preset, let me know, because otherwise I'll do it this weekend.
