### ISSUE TITLE
When changing numeric values on weapons, the last character/digit is cut of

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#391]
When you change the price of a weapon to for example 10 and close the weapon-sheet, only the 1 will be stored and you have to reopen the sheet and add the "0" again.

**Comment by n3dst4** [comment]
Thanks for the report! This looks like a doozy. I guess people mainly use the +/- buttons. Anyway, I should be able to get on it this weekend.

**Comment by n3dst4** [comment]
I made some decent progress on this. I found the underlying cause, which was a change I made a couple releases ago, and fixed it and added some tests around it. I should be able to get a new release out this week.
