### ISSUE TITLE
GM-Note-Field on NPC Sheet

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#618]
Could you include a gm-Notes Field as i had in my version of the new sheet, i don't want to see my players every information about a certain NPC

**Comment by n3dst4** [comment]
Ahh yeah, sorry, I see what you mean. Yes, I'll add that back in.

**Comment by Muwak77** [comment]
And again you delivered, so happy with the result. Keep up the good work :)
