### ISSUE TITLE
Secret-Formatting is not working as expected on Character-Sheets

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#639]
The Secret-Formatting in the Character-Sheets Rich Text Fields does not hide its contend from the players. 
The sheet also still uses the old tiny-mce textfield of which i am not certain how long it will be supportet by foundry itself.

Maybe we could transition to the newer one which also supports a revealeble secret-field.

solving this one or the other way would make my need for a GM-Note-Field on the NPC-Sheet less pressing (Though probably way easier to implement and still useful :) )

**Comment by n3dst4** [comment]
Yeah, I need to look at getting rid of TinyMCE. They said a whie ago that they weren't planning to get rid of of but I suspect they will at some point.

How do you do secrets though? I didn't even know that was a feature 😆

**Comment by Muwak77** [comment]
In Both editors there is a Formatting-Option called "Secret" which is supposed to hide its content from non-GM Users. Its in the Block-formattings in the new Editor and in Custom for Tiny-MCE. 
The new Versions also has a Button where you can show certain Blocks of text. 

I suppose you need to implement some mechanism in the Sheet to make this work, didn't find the solution in my first analysis. 
<img width="585" alt="image" src="https://github.com/n3dst4/gumshoe-fvtt/assets/64545711/9b0cacb2-e821-4226-92c6-3f3f138255f3">

**Comment by n3dst4** [comment]
Definite bug. Depends on #655 but will definitely address.

**Comment by n3dst4** [comment]
So as far as I can see, when you create a "secret" block:

* **Owners** can see the text
* **Observers** and **Limited** see nothing

When an owner clicks Reveal/Aufdecken:

* **Observers** and **Limited**  see the text (and it stays "revealed" until an owner clicks "Hide")

Does that line up with your understanding?

**Comment by Muwak77** [comment]
Totally agree
