### ISSUE TITLE
Tokenizer Compatibility

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#706]
Something is wrong with the tokenizer-module which works fine for most systems but in Gumshoe it does not store the proper image-path in the (Prototype-)Token. AFAIK this should all be basic foundry functionality and not be affected by the system, but for some reason it does not work here and the portrait image is used as a token instead.

**Comment by n3dst4** [comment]
Weird. INVESTIGATOR does do some stuff with token images, maybe I've accidentally broken tokenizer.
