### ISSUE TITLE
Add some delete-Buttons

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#820]
In the Weapon- and Inventorysectios it is nessecary to open an item to delete it. This is kind of inconvenient and it would be cool to have an inline-button for each weapon/item to delete it. 

I don't mind to get this one assigned to implement but wantend to suggest it before working on it.

**Comment by n3dst4** [comment]
Question: how often do you delete items? This is a genuine question - I feel like I don't do it that often whyen I'm playing GUMSHOE games.

My main hesitation is how cluttered thw weapons area is. 

However - I have a suggestion. We could have an `Actions...` menu on each item, and it could contain:

* reload
* transfer to character
* delete

The layout of the weapon row is weird right now - there's extra space on the right which is wasted, so we could fix that at the same time.

WDYT?

**Comment by n3dst4** [comment]
Will fold this into #909
