### ISSUE TITLE
Item Transfer between Actors

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#821]
I'd love to see a button to transfer an item to another pc. I imagine this as follows:

- next to the item we add a "tranfer to" button
- A Dialog opens to select any actor that is visible to the player
- after pressing a ok/confirm the item is removed from the sending characters inverntory and added to the recieving one (maybe vice versa so we don't need to store the data)
- maybe n ingame setting that allows to limit the selection to adjeicent and/or player characters

I can do this one if you approve but i'm not certain if this is already within my skill :)

**Comment by n3dst4** [comment]
Two thoughts:

Did you know you can drag-drop items between character sheets? It won't *delete* the original but it might be enough.

This would have to be inside the item sheet, I'm already concerned about how cluttered the item and (especially) weapons rows are.

**Comment by n3dst4** [comment]
Will fold this into #909
