### ISSUE TITLE
Links are broken in NPC-Sheets

### ISSUE THREAD

**Issue by Muwak77** [n3dst4/gumshoe-fvtt#957]
When you add a link to a journal Entry in the text editor in Notes or GM Notes it doesnt open anymore when you click it,

**Comment by n3dst4** [comment]
I literally just noticed the same thing!! Thanks for the report.  Expect 8.2.1 shortly :)

**Comment by Muwak77** [comment]
Dude, that was quick :)

**Comment by n3dst4** [comment]
Haha :) 

I'm playing with the release process so 8.2.1 isn't properly out yet.
